### ISSUE TITLE
automated conversion of manifest data to parsing/composing of in/out packets

### ISSUE THREAD

**Issue by divanchykhin** [smartanthill/smartanthill-plugin-handler-compiler#1]
In the present embodiment plugin writer has to write his own parsing sequence to get data from an input packet, and writing sequence to write data to the output. In the same time structure of input and output data follows from plugin manifest, and therefore, code related to parsing/composing can be generated automatically thus reducing/eliminating inconsistencies between the manifest and the code.

**Comment by marcosbracco** [comment]
Done at e29dbb9709c2483436f8695e35f33b162e95696e
